// <auto-generated />
using Escola.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escola.Migrations
{
    [DbContext(typeof(EscolaContext))]
    [Migration("20181023001551_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Escola.Models.MinhaEscola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<string>("Nome");

                    b.Property<int>("Quantidade_Alunos");

                    b.Property<int>("Quantidade_Professor");

                    b.Property<string>("Telefone");

                    b.HasKey("ID");

                    b.ToTable("MinhaEscola");
                });
#pragma warning restore 612, 618
        }
    }
}
